### ISSUE TITLE
fenv install with specific channel

### ISSUE THREAD

**Issue by sanghyuk-nam** [fenv-org/fenv#3]
Can I install specific channel's version?
Such as `>fenv install 3.7.10 stable`
It could be better to display channels on `fenv install --list`.
Thank you so much.

**Comment by powdream** [comment]
@sanghyuk-nam 
Thanks for your suggestion. I was also concerned about the output from `flutter doctor -v`.

**Comment by fenv-jerry** [comment]
Done. will be shipped to 0.1.0
